version: '3.11'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py makemigrations phone && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
      - redis
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # Я объединяю celery и celery-beat несмотря на то, что рекомендуется контейнезировать их отдельно
  # Просто у меня не хватает мощностей компьютера держать столько контейнеров
  # Разделение этих сервисов позволяет удерживать отказоустойчивость
  celery:
    build: .
    command: /bin/sh -c 'celery -A backend worker --loglevel=info -B'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
